# Generated by Django 5.0.6 on 2025-08-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_alter_employer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Employer', 'verbose_name_plural': 'Employers'},
        ),
    ]
